---
title: "Generalized Estimating Equations"
output: 
  pdf_document:
    df_print: kable
    includes:
      in_header: Rmarkdown_preamble.tex
geometry: margin=0.5in
fontsize: 11pt
---

<!------------------------------------------------------------------------------>
<!--  ####  KNITR Setup & Script Information   #### -->
<!------------------------------------------------------------------------------>

<!--  ####  KNITR Specs   #### -->
```{r setup, cache=TRUE, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(echo=FALSE, 
                      cache = TRUE, 
                      fig.align = "center",
                      fig.width = 5)
```
***

<!--  ####  Description   #### -->
\begin{center}
\LARGE{\underline{\textbf{Description}}}
\end{center}

This script will produce, and analyze a linear model fit using General Estimating equations.  The script will assume a Poisson distribution with log-link to obtain initial estimates of $\beta$.  

***

<!--  ####  Script Dependencies   #### -->
```{r, echo=FALSE}
library(ggplot2)
library(plyr)
library(nlme)
library(geepack)
library(forcats)
library(gridExtra)
```


<!--  Working Directory  -->       
```{r, echo=FALSE}
WD="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/RBC/Modeling/GEE"
setwd(WD)
```


<!-- Data  &  Variables -->       
```{r, echo=FALSE}
load(file="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/FinalData/InitialModels/InterceptOnly/alldatFilter.RData")
load(file="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/FinalData/InitialModels/InterceptOnly/flowFilter.RData")
load(file="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/FinalData/InitialModels/InterceptOnly/indseqFilter.RData")
load(file="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/FinalData/InitialModels/InterceptOnly/mdataFilter.RData")
load(file="/Users/lee/Documents/Lee/School/CU Denver/MS_Project/Data:Scripts/FinalData/InitialModels/InterceptOnly/seqFilter.RData")
```
***
<!------------------------------------------------------------------------------>


<!------------------------------------------------------------------------------>
<!-- Begin Script -->       
<!------------------------------------------------------------------------------>
```{r, echo=FALSE}
index.malat1=which(rownames(seqFilter)=="MALAT1")
index.cd19=which(rownames(seqFilter)=="CD19")
mala=seqFilter[index.malat1,]
cd19=seqFilter[index.cd19,]
nFeature=mdataFilter$nFeature
nCount=mdataFilter$nCount
Perc.Mt=mdataFilter$Perc.Mt
subject.no=as.factor(mdataFilter$subject.no)
measurement=mdataFilter$measurement.name
dat=data.frame(subject.no, measurement, Perc.Mt, nCount, nFeature, cd19, mala)
dat$logcd19=log(cd19+1, base = exp(1))
dat$logmala=log(mala+1, base = exp(1))
IDgee=dat$subject.no
IDgee=as.factor(IDgee)
IDgee=fct_drop(IDgee)
dat$subject.no=IDgee
```

\vspace{10pt}

# Non-Transformed Model

```{r}
GEEmod=geeglm(mala~ cd19,
              family = "gaussian",
              id=IDgee,
              data = dat,
              corstr = "independence")
print(summary(GEEmod))
print(anova(GEEmod))

plot(mala~cd19, data=dat, main="Model v Orignal Data")
abline(a=coefficients(GEEmod)[1], b=coefficients(GEEmod)[2], col="RED", lwd=4)

# Mean Intercept
print(coefficients(GEEmod)[1])

# Mean Slope
print(coefficients(GEEmod)[2])

dat$fit=fitted(GEEmod)
dat$res=residuals(GEEmod)

p=ggplot(dat, aes(x=fit, y=res, color=subject.no))+
  geom_point()+
  geom_hline(yintercept = 0)+
  ggtitle("Fitted Vs Residual")+
  xlab("Fitted Value")+
  ylab("Residual Value")
p


q=ggplot(dat, aes(sample = res))+
  stat_qq()+
  stat_qq_line()
q
```

# Transformed Model

```{r}
logGEEmod=geeglm(logmala~ logcd19,
              family = "gaussian",
              id=IDgee,
              data = dat,
              corstr = "independence")

coefTable.GEETemp=coef(logGEEmod)
coefTable.GEE=c(coefTable.GEETemp[1], x1, coefTable.GEETemp[2], x1)


print(summary(logGEEmod))
print(anova(logGEEmod))

plot(logmala~logcd19, data=dat, main="Model v Orignal Data")
abline(a=coefficients(logGEEmod)[1], b=coefficients(logGEEmod)[2], 
       col="RED", lwd=4)

# Mean Intercept
print(coefficients(logGEEmod)[1])

# Mean Slope
print(coefficients(logGEEmod)[2])

dat$fit=fitted(logGEEmod)
dat$res=residuals(logGEEmod)

p=ggplot(dat, aes(x=fit, y=res, color=subject.no))+
  geom_point()+
  geom_hline(yintercept = 0)+
  ggtitle("Fitted Vs Residual")+
  theme(legend.position = "none")+
  xlab("Fitted Value")+
  ylab("Residual Value")
p


q=ggplot(dat, aes(sample = res))+
  stat_qq()+
  stat_qq_line()
q

grid.arrange(p,q,nrow=2)
```

<!------------------------------------------------------------------------------>
<!-- End Script -->       
<!------------------------------------------------------------------------------>


<!------------------------------------------------------------------------------>
<!-- Post-Script -->       
<!------------------------------------------------------------------------------>

<!-- Notes:        -->       

<!-- Compilation Errors -->       

<!-- Execution Errors -->

<!-- Next Scripts to Consider -->

<!------------------------------------------------------------------------------>

